### ISSUE TITLE
yun install nginx get errors.

### ISSUE THREAD

**Issue by manuzcom** [nginx/nginx#167]
### Environment
Rocky linux 8.10

### Description
Error installing nginx.

#### yum error
`
[root@server ~]# yum install nginx
nginx stable repo                                                                                                                                                    1.1 kB/s | 1.5 kB     00:01    
Errors during downloading metadata for repository 'nginx-stable':
  - Status code: 404 for http://nginx.org/packages/centos/8.10/x86_64/repodata/repomd.xml (IP: 52.58.199.22)
Error: Failed to download metadata for repo 'nginx-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
[root@server ~]#
`

**Comment by arielcostas** [comment]
Please provide your yum repo configuration for NGINX. If you followed the [RHEL and derivatives package installation](https://nginx.org/en/linux_packages.html#RHEL), the requested repo URL should be `http://nginx.org/packages/centos/8.10/x86_64/repodata/repomd.xml` since it uses `$releasever` which is the major version only (8, instead of 8.10).

**Comment by manuzcom** [comment]
> Please provide your yum repo configuration for NGINX. If you followed the [RHEL and derivatives package installation](https://nginx.org/en/linux_packages.html#RHEL), the requested repo URL should be `http://nginx.org/packages/centos/8.10/x86_64/repodata/repomd.xml` since it uses `$releasever` which is the major version only (8, instead of 8.10).

this is my nginx.repo file.

<img width="604" alt="screenshot_659" src="https://github.com/user-attachments/assets/d91c91ad-6a14-44f1-8baa-a99f0a302152">

**Comment by manuzcom** [comment]
solved. 
i tried this. 

<img width="457" alt="screenshot_660" src="https://github.com/user-attachments/assets/9d8d3f21-35a9-4ed8-8a03-90367eed5a8a">

**Comment by manuzcom** [comment]
@arielcostas thx.

**Comment by arielcostas** [comment]
I tried replicating this on a brand-new Rocky VM, and I didn't have a `/etc/yum/vars/releasever`. Perhaps you or somebody else added it at some point? Deleting the file should do the trick, since and dnf do the substitution with the actual version.

Also, please close the issue here on GitHub if it's already solved.

**Comment by manuzcom** [comment]
I am using the version of Rocky Linux provided by NHN Cloud. 
It is possible that the cloud provider made some minor tweaks to the system. 
Thank you for checking! 
I will close this issue now.
