### ISSUE TITLE
[Feature] "external;" as opposite to "internal;"

### ISSUE THREAD

**Issue by kkmuffme** [nginx/nginx#233]
### Describe the problem this feature solves

When working with large nginx configurations, you sometimes encounter a scenario where you want to add a location block for specific requests, but don't want to modify any internal rewriting.
While this can easily be achieved with named locations for example, it's often not easily possible to change any existing configuration to work with this named location due to various side-effects.

Ideally, there would be an `external;` config option, to mark the location block to not be used in internal requests matching - basically as a counter-part to the existing `internal;`

**Comment by viktorberezikov** [comment]
The `internal` directive specifies that a given location can only be used for internal requests. We do not control the requests from the clients, that's why we have this directive.
As for locations for external requests, all locations are external by default. And we can control/configure whether we access locations after internal redirects. Therefore, such a directive does not seem useful.
