### ISSUE TITLE
Index internal redirection processing

### ISSUE THREAD

**Issue by fgh42** [nginx/nginx#240]
nginx 1.27.1

In my setup I want to display a completely different page from a different directory for the "/" URI. I have the following configuration:

server
{
	.
	.
	.

	root /www/directory1; # first 'root' directive
	
	location = /
	{
		root /www/directory2; # second 'root' directive
		index index.html;
	}
	
	location = /index.html
	{
		root /www/directory2; # third 'root' directive
	}

	location /
	{
		index index.php;
		try_files $uri $uri/ /index.php?$args;
	}
	
	.
	.
	.
}

According to the documentation the index directive causes internal redirect (even in =/ location, I learned it the hard way, but OK), but it looks like nginx first checks for existence of the file index.html in the directory /www/directory1 (set by the root directive at the server level) and only after that it displays /www/directory2/index.html as expected. If I delete the file /www/directory1/index.html or the second root directive, the request for "/" URI fails and the nginx debug log shows that nginx unsucessfully tried to stat() /www/directory1/index.html. Is this intentional behaviour? If yes, what is the purpose? I'd expect the request to be completed even without the second root directive.

**Comment by viktorberezikov** [comment]
I would like to highlight two sentences from the `index` documentation: "Defines files that will be used as an index" and "Files are checked in the specified order". This means that before redirecting, nginx should make sure that the file exists. And it checks the files on the list within the `location = /`. And if one of the specified files exists, a redirect occurs. Therefore, this is expected behavior.
More information here:
https://nginx.org/en/docs/http/ngx_http_index_module.html#index

**Comment by fgh42** [comment]
Ah, I understand now, it's necessary to process the index directive, especially with multiple arguments i.e. multiple possibilities for the index file to choose from.
