### ISSUE TITLE
Caching dynamically compressed files

### ISSUE THREAD

**Issue by nisbet-hubbard** [nginx/nginx#290]
### Describe the feature you'd like to add to nginx

Storing compressed files returned by on-the-fly brotli filter in cache path.

### Describe the problem this feature solves

This is one of the remaining areas where nginx falls short and can’t match Apache httpd’s offering at present. Whereas Apache [caches and serves compressed files](https://serverfault.com/a/220418), nginx only saves the uncompressed response and requires on-the-fly compression _for each subsequent request_ (or else manual compression beforehand).

This also makes `SSL_sendfile()` much less effective, having to be disabled whenever such repeated compression happens.

### Additional context

Previous request: https://forum.nginx.org/read.php?11,283440,283440

**Comment by dvershinin** [comment]
Actually this can be achieved by NGINX alone. 

You can use `proxy_cache` (set up a "front-end" caching and "backend" PHP/compression NGINX configurations) and then configure your "front-end" proxy cache key to be based on normalized `Accept-Encoding` header. Roughly (untested, consider as more of a pseudo-code to begin with):

```nginx
# front-end with caching
server {
    …
    # listen on actual server ports
    location / {
        proxy_pass http://backend;
        proxy_cache myZone;
        gzip off;
        brotli off;
        # normalized_http_accept_encoding has to be created via `map` to ensure `Accept-Encoding:` values are normalized
        # to just the three possible variants like `Accept-Encoding: gzip`, `Accept-Encoding: br` and an empty one.
        proxy_cache_key "$scheme$request_method$host$request_uri $normalized_http_accept_encoding";
        # for consistency with normalized encoding, instruct backend to use it
        proxy_set_header Accept-Encoding "$normalized_http_accept_encoding";
    }
}
# backend with PHP and compression
server {
    …
    # listen on designated private ports
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
        ...
    }
    gzip on;
    brotli on;
}
```

This of course, will introduce a bit of latency for additional communication between NGINX "instances", although it may be negligible on the same server and provided the benefits outweighs it.

Introducing direct support for this in NGINX is highly unlikely as the order of body filters like gzip is more or less set to be after fastcgi cache already did its job. Plus an issue with normalization of `Accept-Encoding` header as mentioned in the linked discussion would make it never work out of the box anyway (without severely polluting your disk cache with unlimited amount of entries due to clients sending numerous distinct values for that header).

**Comment by nisbet-hubbard** [comment]
I didn’t think of this possibility! Absolutely love it.

Will do a PR and get the technique documented.

**Comment by zingaburga** [comment]
> Plus an issue with normalization of `Accept-Encoding` header as mentioned in the linked discussion would make it never work out of the box anyway (without severely polluting your disk cache with unlimited amount of entries due to clients sending numerous distinct values for that header).

The way I'd do it is to completely ignore the Accept-Encoding header and *always* store the cache entry compressed (possibly with associated Content-Encoding header).

Putting Brotli aside, the *vast* majority of clients support gzip, and for the few that don't, the gunzip module can deal with.  Decompression is also generally faster than compression, so one would expect a large reduction in CPU usage this way (plus reduced cache footprint and disk I/O).

Of course, things get more complicated if you want to support Brotli+gzip (i.e. more than one compression method).  I'd imagine this  would only work well if you enable only one compression method.

> the order of body filters like gzip is more or less set to be after fastcgi cache already did its job. 

The way I'd see it is this adds a *new* filter, between the upstream response and the cache.  Trying to reorder the body filter would mean that gunzip wouldn't work (i.e. response -> gzip -> cache -> gunzip -> response).

This can, of course, be done with a second nginx instance, as previously suggested.  Unfortunately, the additional overhead makes this less attractive, plus many distros don't make it easy to run two instances of the same service on the same machine.

**Comment by HanadaLee** [comment]
> > Plus an issue with normalization of `Accept-Encoding` header as mentioned in the linked discussion would make it never work out of the box anyway (without severely polluting your disk cache with unlimited amount of entries due to clients sending numerous distinct values for that header).
> 
> The way I'd do it is to completely ignore the Accept-Encoding header and _always_ store the cache entry compressed (possibly with associated Content-Encoding header).
> 
> Putting Brotli aside, the _vast_ majority of clients support gzip, and for the few that don't, the gunzip module can deal with. Decompression is also generally faster than compression, so one would expect a large reduction in CPU usage this way (plus reduced cache footprint and disk I/O).
> 
> Of course, things get more complicated if you want to support Brotli+gzip (i.e. more than one compression method). I'd imagine this would only work well if you enable only one compression method.
> 
> > the order of body filters like gzip is more or less set to be after fastcgi cache already did its job.
> 
> The way I'd see it is this adds a _new_ filter, between the upstream response and the cache. Trying to reorder the body filter would mean that gunzip wouldn't work (i.e. response -> gzip -> cache -> gunzip -> response).
> 
> This can, of course, be done with a second nginx instance, as previously suggested. Unfortunately, the additional overhead makes this less attractive, plus many distros don't make it easy to run two instances of the same service on the same machine.

You don't need to run two nginx instances, you can do this on one instance, using different listening ports to distinguish between layer 1 and layer 2.

For the local loopback TCP overhead problem, you can consider using unixsocket instead of TCP for communication between layer 1 and layer 2.

Regarding the Accept-Encoding header normalization issue, I developed a module specifically for this function: https://github.com/HanadaLee/ngx_http_compress_normalize_module

However, as mentioned earlier, there is definitely additional overhead. But I believe that unless the qps of your service is high enough to cause nginx to have a very heavy load, the two-tier architecture + unixdomain should not add too much overhead. For use cases such as php applications, the bottleneck is unlikely to appear in nginx.

**Comment by zingaburga** [comment]
> you can do this on one instance, using different listening ports to distinguish between layer 1 and layer 2.

Ah good point - didn't think about that.

Other than overhead, it still has a few warts, for example, if you have a min_uses directive, the upstream nginx won't be able to act on it.  But it could suffice as a hacky workaround for some.

**Comment by HanadaLee** [comment]
> > you can do this on one instance, using different listening ports to distinguish between layer 1 and layer 2.
> 
> Ah good point - didn't think about that.
> 
> Other than overhead, it still has a few warts, for example, if you have a min_uses directive, the upstream nginx won't be able to act on it. But it could suffice as a hacky workaround for some.

The two levels use different cache keys, so there will be no min_use problem

**Comment by zingaburga** [comment]
> The two levels use different cache keys, so there will be no min_use problem

Sorry, I don't quite get the setup you propose.

The way I understand it is the upstream nginx does the compressing, whilst the downstream nginx does the caching.  So why is there two levels of caching?

**Comment by HanadaLee** [comment]
> > The two levels use different cache keys, so there will be no min_use problem
> 
> Sorry, I don't quite get the setup you propose.
> 
> The way I understand it is the upstream nginx does the compressing, whilst the downstream nginx does the caching. So why is there two levels of caching?

If you only use cache in the first layer, the min_uses statistic will not be a problem. I just answered your question about min_uses.

**Comment by zingaburga** [comment]
Sorry, I still don't understand you.  If you're caching in the upstream nginx, you're not caching the compressed response.  The reason for two layers is that you need the first to do the compression so that the second can do the caching.  Doing caching in the first layer defeats the purpose of having two layers.

**Comment by HanadaLee** [comment]
> Sorry, I still don't understand you. If you're caching in the upstream nginx, you're not caching the compressed response. The reason for two layers is that you need the first to do the compression so that the second can do the caching. Doing caching in the first layer defeats the purpose of having two layers.

What I mean is, assuming you need two layers of cache, using different cache keys will not affect the min_uses count. If you only configure cache on the first layer, there will be no impact on the min_uses count at all. 

I am just explaining this issue: `it still has a few warts, for example, if you have a min_uses directive`

So far, apart from the extra overhead, no other problems have been found. Or the problems found can be solved.

**Comment by zingaburga** [comment]
> assuming you need two layers of cache

Who needs two layers of cache?  I thought this whole thing was being discussed with only one level.

> I am just explaining this issue

The issue is that the upstream nginx isn't aware of min_uses in the downstream (caching) nginx.  Force compressing every response, even if it won't be cached (due to min_uses), is a waste of CPU cycles if the client doesn't accept compressed responses.
