### ISSUE TITLE
Dependency error installing NGINX on Rocky Linux after 9.5 release

### ISSUE THREAD

**Issue by guillermo-jano** [nginx/nginx#343]
Following the [installation procedure](https://nginx.org/en/linux_packages.html#RHEL) for RHEL and derivatives fails on Rocky Linux after 9.5 [release](https://rockylinux.org/news/rocky-linux-9-5-ga-release):

```
# dnf install nginx nginx-module-njs
Last metadata expiration check: 0:02:42 ago on Wed Nov 20 15:33:33 2024.
Error: 
 Problem: package nginx-module-njs-1:1.26.2+0.8.7-1.el9.ngx.x86_64 from nginx-stable requires nginx-r1.26.2, but none of the providers can be installed
  - cannot install both nginx-2:1.20.1-20.el9.0.1.x86_64 from appstream and nginx-1:1.26.2-1.el9.ngx.x86_64 from nginx-stable
  - cannot install the best candidate for the job
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

Before the 9.5 update, DNF would install both packages from the `nginx-stable` repository, but now the `nginx` package from `appstream` is chosen as the best candidate and that creates the dependency conflict shown above. Adding `--nobest` works around the issue but then whenever you run `dnf update` you will get an error

```
# dnf update
Last metadata expiration check: 0:07:41 ago on Wed Nov 20 15:33:33 2024.
Error: 
 Problem: package nginx-module-njs-1:1.26.2+0.8.7-1.el9.ngx.x86_64 from @System requires nginx-r1.26.2, but none of the providers can be installed
  - cannot install both nginx-2:1.20.1-20.el9.0.1.x86_64 from appstream and nginx-1:1.26.2-1.el9.ngx.x86_64 from @System
  - cannot install both nginx-2:1.20.1-20.el9.0.1.x86_64 from appstream and nginx-1:1.26.2-1.el9.ngx.x86_64 from nginx-stable
  - cannot install the best update candidate for package nginx-module-njs-1:1.26.2+0.8.7-1.el9.ngx.x86_64
  - cannot install the best update candidate for package nginx-1:1.26.2-1.el9.ngx.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

And need to specify `--nobest`  as well to proceed (`--allowerasing` will uninstall the NGINX version and install the one from AppStream instead).

I have tried disabling the `nginx` AppStream module with `dnf module disable nginx php` but that does not change anything. There is an `nginx` package in AppStream that will be installed even if the module is disabled and is considered a best candidate than the one in the NGINX repository.

After a little investigation, looks like the reason for the change is the NGINX package in 9.5 has an `Epoch` of 2 so it is preferred over NGINX's (`Epoch` 1) even if the version is higher:

#### 9.4 version:

    Name        : nginx
    Epoch       : 1
    Version     : 1.20.1
    Release     : 16.el9_4.1

#### 9.5 version:

    Name        : nginx
    Epoch       : 2
    Version     : 1.20.1
    Release     : 20.el9.0.1

#### NGINX repository version:

    Name        : nginx
    Epoch       : 1
    Version     : 1.26.2
    Release     : 1.el9.ngx

As per the [`Epoch` directive definition](https://docs.redhat.com/fr/documentation/red_hat_enterprise_linux/9/html/packaging_and_distributing_software/epoch-scriplets-and-triggers_advanced-topics#packaging-epoch_epoch-scriplets-and-triggers), epoch takes precedence over the version, so since 2 > 1, the `nginx` package in 9.5 is preferred over the one in the NGINX repository even if 1.20.1 < 1.26.2. This was not the case in 9.4 since both packages had the same epoch (1).

I have not had the opportunity to test on a RHEL system yet so I am not sure if this is a Rocky Linux specific issue or it applies to RHEL 9.5 and other derivatives as well.

**Comment by thresheek** [comment]
Hello @guillermo-jano! 

Thanks for letting us know.  The behaviour change seems to stem from https://git.almalinux.org/rpms/nginx/commit/80ab6cb25cce433c995c8cb8efd9ff281b42ca43 but I'm failing to find what `RHEL-33939` is about.

Our only way to fix that is to probably bump Epoch again.

**Comment by guillermo-jano** [comment]
I found this https://www.findbugzero.com/operational-defect-database/vendors/rh/defects/RHEL-33939

**Comment by thresheek** [comment]
Yep, a correct link would be https://issues.redhat.com/browse/RHEL-33939 too.

Indeed, we'd need to bump Epoch again.

**Comment by guillermo-jano** [comment]
Do you have an ETA for this change? We have a product release soon and depending on whether this is fixed before it or not we may need to document a workaround. No pressure, just to know :)

**Comment by creativelyinspired** [comment]
Also just wanted to note this has broken existing installs and in our case caused downtime due to incompatible directives between the versions. The epoch change also causes "dnf update" to replace mainline builds with 1.20 but, Nginx instances with config files using the "http2 on" directive(and perhaps others) then fail to start as that directive isn't supported by 1.20.

using excludepkgs=nginx* on the appstream repo as a workaround for the moment

**Comment by thresheek** [comment]
I think we can fix the issue today, by providing 1.26.1-2 and 1.27.2-2 packages in the repos just for RHEL 9 and derivatives.  See https://github.com/nginx/pkg-oss/pull/15 for a proposed fix.

I'll build the packages & run tests to make sure we're not breaking something unexpected;  I'll report back here when fixed repos are live.

**Comment by thresheek** [comment]
Newer versions of packages are now published for both stable and mainline repos for RHEL 9.  Please check if they fix the issue for you.

Thanks!

**Comment by guillermo-jano** [comment]
> Please check if they fix the issue for you

I can confirm this fixes the issue for us, thank you!

**Comment by LawrenceK** [comment]
This can cause an issue where a server was deployed after RHEL bumped the epoch so instead of installing from nginx-mainline it installs an older version (from @appstream). Such that when you later do yum upgrade after this change you get errors:

Error: Transaction test error:
  file /etc/logrotate.d/nginx from install of nginx-2:1.27.2-2.el9.ngx.x86_64 conflicts with file from package nginx-core-2:1.20.1-20.el9.0.1.x86_64
  file /etc/nginx/mime.types from install of nginx-2:1.27.2-2.el9.ngx.x86_64 conflicts with file from package nginx-core-2:1.20.1-20.el9.0.1.x86_64
  file /etc/nginx/nginx.conf from install of nginx-2:1.27.2-2.el9.ngx.x86_64 conflicts with file from package nginx-core-2:1.20.1-20.el9.0.1.x86_64
  file /usr/sbin/nginx from install of nginx-2:1.27.2-2.el9.ngx.x86_64 conflicts with file from package nginx-core-2:1.20.1-20.el9.0.1.x86_64
  file /var/log/nginx from install of nginx-2:1.27.2-2.el9.ngx.x86_64 conflicts with file from package nginx-core-2:1.20.1-20.el9.0.1.x86_64

To get round this I used 
yum shell
remove nginx-core
install nginx
run

Also removed nginx-filesystem
